development:
  adapter: postgresql
  encoding: unicode
  database: vh_awesome_forum
  pool: 5
  username: postgres
  password: golao123

test:
  adapter: postgresql
  encoding: unicode
  database: vh_awesome_forum
  pool: 5
  username: postgres
  password: golao123